### ISSUE TITLE
Feature request: Add releases to a playlist

### ISSUE THREAD

**Issue by the-code-creator** [jakubito/spotify-release-list#1]
Hello, I really like the Spotify tool.
I have a feature request: There should be an option to put all new releases of your followed artists into a private playlist.
You should be able to specify a starting date, for example 2020-01-02
All songs, which get released after that date, will be automatically added to the playlist.
If the playlist reaches a specified limit (e.g. 9500 songs), then a new playlist will be created.

Would be cool if this useful feature will get implemented!👍

**Comment by jakubito** [comment]
Hello Michael,
Thanks for the suggestion. I put it on my to-do list :)

Cheers,
Jakub

**Comment by the-code-creator** [comment]
### 🥳

**Comment by jakubito** [comment]
Hello @the-code-creator 👋

I just released new version with the ability to create playlists from existing releases. Enjoy!

Jakub
