### ISSUE TITLE
For Spicetify?

### ISSUE THREAD

**Issue by FiftyFour7250** [jakubito/spotify-release-list#12]
Hey. I know it's outside of your project, but maybe you'd be interested? Do you know about [Spicetify](https://github.com/khanhas/spicetify-cli)? This is tool for modifying the appearance and capabilities of Spotify. [It also has New Releases](https://github.com/khanhas/spicetify-cli/wiki/Extensions#new-release), but unlike your site, it doesn't show Appearances,  only Albums and Singles, which is why a lot of songs are skipped. I [asked](https://github.com/khanhas/spicetify-cli/issues/450) author to add Appearances, but he thinks that they will be superfluous, although he said that he can help. Maybe you want to make your own version of the extension for Spicetify? I'm not programmer, but your site and its extension on javascript, so maybe it's not that hard...

**Comment by jakubito** [comment]
Hi, thanks for the suggestion. I didn't know about Spicetify until now. 

I've looked into it and I think I'll pass. I don't have time and motivation for maintaining another project and making sure it's working properly in all future versions of Spicetify/Spotify. I'm already too slow delivering new features on my app and can't imagine committing myself to a new project like this.
