### ISSUE TITLE
Feature Request: Filter out duplicate entries

### ISSUE THREAD

**Issue by mzur** [jakubito/spotify-release-list#14]
My release list contains many duplicate entries like this:

![image](https://user-images.githubusercontent.com/2457311/117192083-9b51ac80-ade1-11eb-9625-f33c86d260cd.png)

Do you have an idea what could cause this? I'm willing to contribute if you can point me in the right direction.

**Comment by jakubito** [comment]
Hi Martin,

What you are seeing is exactly the same data that is returned from Spotify API. Sometimes, an album is represented by multiple entries, each with a unique ID and different copyright wording. I'm not sure why labels do this, I assume there are some legal reasons behind it. If you search for London Grammar, you will see it's the same for all of their singles too:


I haven't encountered this too often so I've never felt I need to come up with a workaround.

**Comment by jakubito** [comment]
Hi Martin,

What you are seeing is not a bug - it is exactly the same data that is returned from Spotify API. Sometimes, an album is represented by multiple entries, each with a unique ID and different copyright wording. I'm not sure why labels do this, I assume there are some legal reasons behind it. If you search for London Grammar, you will see it's the same for the rest of their music too:

![image](https://user-images.githubusercontent.com/8123702/117211261-9f63d700-adad-11eb-93d2-4a042b986cab.png)

I haven't encountered this too often so I've never felt I need to come up with a workaround. My concern is how to pick the right entry from an array of duplicates - it's not as trivial as it seems. I can explain more if you are interested. I'd love to get some help on this project! 🙂

**Comment by mzur** [comment]
Maybe an opt-in to filter out entries with the same date, title and artist name would be a reasonable compromise. Even if you can't be sure that its the same title etc. the probability to filter out the wrong thing should be low (and its opt-in).

**Comment by jakubito** [comment]
[v2.0.1](https://github.com/jakubito/spotify-release-list/releases/tag/v2.0.1)

**Comment by mzur** [comment]
Thanks a lot for implementing this! Unfortunately I found that Spotify makes this even harder with different upper- and lowercase characters :unamused: 

![image](https://user-images.githubusercontent.com/2457311/128698951-dfd082c1-1096-4f51-91a4-d9da1f0875f9.png)

Maybe the filter should only use lowercase titles.

**Comment by jakubito** [comment]
@mzur This is now fixed in [v2.0.2](https://github.com/jakubito/spotify-release-list/releases/tag/v2.0.2)

**Comment by mzur** [comment]
Thanks, you're awesome 😊

**Comment by mzur** [comment]
Spotify also swaps round brackets with square brackets :facepalm: I don't think that these duplicates can also be filtered out without handling every single edge case, so this information is just for the record.

![image](https://user-images.githubusercontent.com/2457311/130187797-9b45ba1a-122b-498a-b5eb-6770345635b3.png)

**Comment by jakubito** [comment]
Ugh, this is very annoying. I don't think Spotify is to blame for this though. As far as I understand, it's a distributor's responsibility to submit properly named releases. I honestly have no idea why they submit the same release twice, only with different brackets in the title. It makes no sense 🙄

I will update the filter to treat all brackets the same, but I'm sure there are other edge cases. Please keep adding your findings here and I'll do my best to make it as robust as possible. Thank you!

**Comment by affinage** [comment]
Found one more case: different apostrophe signs.

screenshot from spotifyreleaselist:
<img width="873" alt="Screen Shot 2021-10-02 at 10 12 36 PM" src="https://user-images.githubusercontent.com/4787857/135729216-0d7fa3d5-251e-41bb-9e54-452089368ffa.png">

screenshot from spotify
![1633202163656](https://user-images.githubusercontent.com/4787857/135729279-cc8ba88f-ac35-42bd-bbaf-a4aa2d05502d.png)

albums for reference: 
[**I'm In Love (Redondo Remix)**](https://open.spotify.com/album/7Fd8qGKLW01uHJdXggi87l)
[**I’m in Love (Redondo Remix)**](https://open.spotify.com/album/2eczxusBkTlNlWU1b8nZnS)

**Comment by jakubito** [comment]
@mzur @affinage The filter has been updated in [v2.0.3](https://github.com/jakubito/spotify-release-list/releases/tag/v2.0.3) to address edge cases you provided.
