### ISSUE TITLE
Feature Request: Saving/Pinning albums to be listened to later and checking off songs you have listened to already

### ISSUE THREAD

**Issue by rinyafii** [jakubito/spotify-release-list#15]
Hi! I really like this app.
This has been amazing, but there is one thing I wish it had. Some kind of "save for later" system to remember albums for later and/or a system that lets you hide songs you have already listened to.

When i'm going though my releases, I like to listen to all the singles first. Then I go back through and listen to the albums since they take more time. It's a bit hard remembering what I went by. 

My idea would be to hide songs/albums you have already listened to by checking them off, or having a "save for later" menu at the top. 

Thanks for the amazing app! (P.S. sorry if I don't format this right, I have never used GitHub before)

**Comment by jakubito** [comment]
I like this 👍   having some kind of favorites system could be useful. You could then filter by favorites and subsequently export them to a playlist.

**Comment by jakubito** [comment]
Added in [v2.1.0](https://github.com/jakubito/spotify-release-list/releases/tag/v2.1.0)
