### ISSUE TITLE
Add a new filter to exclude remixes

### ISSUE THREAD

**Issue by jakubito** [jakubito/spotify-release-list#17]
Having the ability to filter out remixes would be a useful way to reduce clutter. 

I think the most obvious and straightforward way to detect a remix release is to check for `remix` string inside a title (case-insensitive). This would be visually similar to the existing `Exclude Various Artists` checkbox filter.

**Comment by schwartzadev** [comment]
I can take this on!

**Comment by jakubito** [comment]
[v3.1.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.1.0)
