### ISSUE TITLE
Feature Request: Blacklisting labels

### ISSUE THREAD

**Issue by sc113** [jakubito/spotify-release-list#19]
As was discussed here: #4 
Some VA albums are notable and equal to albums with the new tracks, but most VA compilations are worth to be ignored. The same labels are responsible for most of the unworthy compilations and it would be useful to add them to the blacklist, instead of disabling all VA releases.

**Comment by sc113** [comment]
I forgot to mention that it will be important to blacklist only certain types of releases (VA or compilations) from a particular labels.

**Comment by jakubito** [comment]
[v3.0.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.0.0)

**Comment by capellavacancies** [comment]
A question about this feature, I'd like to block a label called Geomagnetic Records, its name gets displayed on spotify like this:
Geomagnetic Records
2022 Geomagnetic Records
© 2022 Geomagnetic Records
℗ 2022 Geomagnetic Records

Which line should I use ?
Thanks

**Comment by jakubito** [comment]
@capellavacancies The easiest way to block a label is to do the following:

1. Enable extra data fetching ![Screen Shot 2022-08-29 at 23 49 45](https://user-images.githubusercontent.com/8123702/187369792-16339cc0-bfef-4606-b0fb-a9f38cce62a2.png)
2. Display labels ![Screen Shot 2022-08-29 at 23 49 55](https://user-images.githubusercontent.com/8123702/187369809-d8971045-9378-452b-907b-b9178b269580.png)
3. Refresh
4. Click on a label and choose one of the two options ![Screen Shot 2022-08-29 at 23 50 40](https://user-images.githubusercontent.com/8123702/187369818-4a79a23e-8b29-4a9c-83c3-343f9132ac41.png)
