### ISSUE TITLE
Feature Request: Number of tracks in the release

### ISSUE THREAD

**Issue by sc113** [jakubito/spotify-release-list#20]
This would be useful for distinguishing repetitive releases, and in some other specific cases.

**Comment by capellavacancies** [comment]
I do agree, but I think it could be even better to get advantage of the new spotify release tag: album, ep, single. I wonder what criteria spotify-release-list used before this to distinguish between different kind of releases. btw I still think that plain number of tracks could be useful

**Comment by jakubito** [comment]
@sc113 Thanks for the suggestion.

@capellavacancies I'm not aware of anything new - which new tags are you talking about? The app has always used `album_group` property for categorizing releases.

**Comment by jakubito** [comment]
[v2.3.0](https://github.com/jakubito/spotify-release-list/releases/tag/v2.3.0)
