### ISSUE TITLE
"Invalid request" every time I try to log in

### ISSUE THREAD

**Issue by teiraaa** [jakubito/spotify-release-list#24]
The website just logged me out and any time I try to log in back again a red pop-up shows saying "Invalid request", I've tried this on two devices already and I've changed the password and it still says the same -- is there any problem w/ the API?

**Comment by jakubito** [comment]
I've tested desktop Chrome and mobile Safari and I'm not seeing any issues. Which browsers are causing the error? Can you confirm the version says **2.0.0 (b67d20f)**?

**Comment by puzatt** [comment]
> I've tested desktop Chrome and mobile Safari and I'm not seeing any issues. Which browsers are causing the error? Can you confirm the version says **2.0.0 ([b67d20f](https://github.com/jakubito/spotify-release-list/commit/b67d20f90039c1ccaaca4cadbc7401afb4e0cd53))**?

![Screenshot_20210703-084357__01](https://user-images.githubusercontent.com/86867423/124344499-3e088a80-dbdb-11eb-92f0-21dc1020b802.jpg)
![Screenshot_20210703-084332__01](https://user-images.githubusercontent.com/86867423/124344500-3f39b780-dbdb-11eb-955e-de6271e1f436.jpg)

Mobile chrome, desktop chrome, mobile opera

**Comment by jakubito** [comment]
@teiraaa @puzatt Can you please try to update to `Version 2.0.4 (db23b88)` and let me know if the problem still persists? Thanks.

**Comment by jakubito** [comment]
No response; closing this for now
