### ISSUE TITLE
Invalid request Problem

### ISSUE THREAD

**Issue by ghost** [jakubito/spotify-release-list#25]
it's shows me "Invalid request" when i try to login from brave browser desktop

**Comment by ghost** [comment]
I'm having the same issue. Microsoft Edge Version 93.0.961.44 (Official build) (64-bit).

**Comment by jakubito** [comment]
@beshoyy @twilightened Can you please try to update to `Version 2.0.4 (db23b88)` and let me know if the problem still persists? Thanks.

**Comment by jakubito** [comment]
No response; closing this for now
