### ISSUE TITLE
Color Picker does close after first click

### ISSUE THREAD

**Issue by EtzBetz** [jakubito/spotify-release-list#26]
In the recent version of spotify-release-list, in the "app", the color picker bugs out on my system. I click on the color that I want to change, the picker opens fine. Now when I click on a color or on the color-range bar, the picker closes on mousedown and either uses the color i just entered, or (seems to be dependant on popup and click position) just uses #000000 as color. also, when he would accept the correct color, and you keep dragging the mouse, the accepted color will jump to black as well.

Using Chrome on macOS with the App Extension thing.

**Comment by jakubito** [comment]
Thanks, not sure how I missed this. Will fix it asap.

**Comment by EtzBetz** [comment]
You're welcome :)

Thanks for this nice client.

**Comment by jakubito** [comment]
Fixed in [v2.0.3](https://github.com/jakubito/spotify-release-list/releases/tag/v2.0.3)
