### ISSUE TITLE
Include releases from artists whose songs I've saved

### ISSUE THREAD

**Issue by schwartzadev** [jakubito/spotify-release-list#28]
I'd love to see this as an enhancement and I'd be interested in adding the feature myself if it's something the maintainers would support!

This is a really neat platform, but I feel like it's of limited use to me since I typically save songs from artists that I like, and only rarely actually follow those artists.

I'm imagining a feature (perhaps disabled by default) where users can toggle to include artists whose songs they've saved. This would then: conditionally (upon enabling this setting) include those artists here to be included in the sync for new releases.

This would include:
* Adding a `getUserLikedSongsArtists` (perhaps with a better name 😅) method here that returns a list of the artists whose songs the user has liked. This would be in the `api.js` file:
https://github.com/jakubito/spotify-release-list/blob/b67d20f90039c1ccaaca4cadbc7401afb4e0cd53/src/api.js#L48
* Adding a setting to toggle this functionality
* Updating `sync.js` to include the artists from `getUserLikedSongsArtists` if the setting is enabled.
https://github.com/jakubito/spotify-release-list/blob/74b53f49ac1a18b716a195fc08d4e1293fb52b47/src/sagas/sync.js#L70

Please let me know if you'd be interested in a PR for this functionality!

**Comment by jakubito** [comment]
Thanks for sharing the idea, I like it! I'm the only developer/maintainer on this project - feel free to create a PR and I will be happy to merge it if it looks good. 

I don't see this in your outline above, but you will also have to ask for additional scope [user-library-read](https://developer.spotify.com/documentation/general/guides/authorization/scopes/#user-library-read), which makes it a little bit more complicated. Remember this scope has to be optional (only requested when the option is enabled).

**Comment by somegirl** [comment]
This is a great enhancement, but just a thought - personally I'd love to see a setting for minimum number of songs liked - in other words, I'm not interested in new releases for every artist who has one song I've liked, but if I've liked, say, three or five of their songs, then I'd want to include them. It would be great if the setting is fully customizable (i.e. I could pick any number I want - 3, 5, 7, 17, whatever).

**Comment by jakubito** [comment]
A great idea @somegirl, I'll make sure to include a setting for the minimum number of songs liked

**Comment by jakubito** [comment]
This is partially done in [v3.1.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.1.0)
I forgot to add the minimum number of songs liked option. I will include it in a later release

**Comment by jakubito** [comment]
[v3.1.1](https://github.com/jakubito/spotify-release-list/releases/tag/v3.1.1)

**Comment by somegirl** [comment]
Very nice! I was inspired to make a small donation. (If I ever hit the big bucks I'll make sure to give more. ;-) )
