### ISSUE TITLE
Replace last created "New Release" Playlist

### ISSUE THREAD

**Issue by Erik262** [jakubito/spotify-release-list#32]
Very nice tool!!!

I'm curious about whether it is possible to replace the previously created playlist with the new one, created from this tool again? Now it is always creating a playlist with the same name.

**Comment by LNS-MrGoodkat** [comment]
@jakubito is this something you are working currently on?

**Comment by jakubito** [comment]
@LNS-MrGoodkat No; I've stopped building new features for now

**Comment by jakubito** [comment]
[v3.7.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.7.0)
