### ISSUE TITLE
Add "Past 2 weeks" time period option

### ISSUE THREAD

**Issue by FreekBes** [jakubito/spotify-release-list#34]
First of all, great application! I'm using it as my homepage on my web browser so that I never miss new releases.

However, I use the website on multiple computers, and due to it using local storage, sometimes it's been more than a week since it last refreshed. I'm following quite a lot of artists on Spotify, thus when refreshing, everything tends to get quite slow. This might not be related to the feature I'm requesting here, but hey, thought I'd also share how I use your work for some background :)

Anyways, I usually check out all new releases within 2 weeks, so the "Past week" time period setting doesn't work for me, while the "Past month" option might be a little much again. Thus, I'm requesting to add a "Past 2 weeks" option to find some middle ground there.

**Comment by jakubito** [comment]
[v3.1.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.1.0)
