### ISSUE TITLE
Filtering viewed releases in the list

### ISSUE THREAD

**Issue by NewUAM** [jakubito/spotify-release-list#38]
Sorry for my English, I'm writing from Ukraine.

New releases in the list often appear in 2-3 days. I don't know if others have this problem. Maybe it happens to me because of the large number of tracked artists (about 2000, I need them to create playlists for my project).

I'm not technically strong, but I suspect the problem is on Spotify's side. Therefore, there is such a proposal: to give the opportunity to mark the viewed tracks so that after updating the list they do not appear again. This will make it easier to find tracks that did not appear on the list on the day of release.

Huge thanks for this product! It is perfect for my needs. I can't imagine how I would have worked without it.

**Comment by jakubito** [comment]
@NewUAM Please check out the new version **3.5.0**, which includes a new album history tracking feature. This adds a new filter that should cover your requirements

**Comment by NewUAM** [comment]
Thank you so much! This is just what I wanted!
