### ISSUE TITLE
Customize Artists Tracked

### ISSUE THREAD

**Issue by shelaffs** [jakubito/spotify-release-list#39]
Hi there! I just started using this tool today and really appreciate that it exists! I love the ability to export all new releases into a playlist for the easiest listening experience.

I'm wondering if there is a way to customize the artist list, similar to how you have a block list for labels. 

For example, my settings are set to pull new releases from all followed artists, and those I have 3+ saved songs by. In some instances, I have several saved songs by an artist, but am not interested in new releases from them, and would like the option to block them from future notifications without removing the saved songs I have. Is there any possibility this could be an added?

Thank you!

**Comment by jakubito** [comment]
Hi @shelaffs, [3.6.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.6.0) introduces artist blocklist
