### ISSUE TITLE
Custom Search

### ISSUE THREAD

**Issue by capellavacancies** [jakubito/spotify-release-list#40]
Hello, question: is there a way to search for a specific month/year in the past ?
like 

October 2021
or
Year 2020

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/58681964/194292014-7fabbdde-bcb5-42de-9b89-107cdea82cb0.png">

**Comment by jakubito** [comment]
You can override "Time period" setting by changing "days" property in the import setting screen. Just change it to something like `1000` to get past 3 years of releases. Beware, this is not officially supported and may take a long time

![image](https://user-images.githubusercontent.com/8123702/195238652-b899f988-ae68-4d38-b972-d30998856767.png)
