### ISSUE TITLE
Not retrieving releases/searching properly

### ISSUE THREAD

**Issue by KatyLB** [jakubito/spotify-release-list#42]
As of today the app is not retrieving more than a few releases and is not searching properly.

The search goes through very fast and only returns a few releases from the past month, yesterday many more were showing than this, it seems to not be retrieving releases properly.

It seems that the artists it does retrieve appear multiple times, so the issue seems to be that it's only gathering data for a fraction of the artists it should.

I don't know if Spotify is blocking it or there's an API issue but normally the search takes a minute or two to progress gradually, and then shows all releases for the artists I follow.

![image](https://user-images.githubusercontent.com/37089178/222206996-cac188dc-6ff8-4a8c-81a8-1b9fe6300262.png)

**Comment by jakubito** [comment]
Hi, I can confirm the issue exists on my side as well.
It seems there is a bug with API returning the first 50 followed artists only, that's why it's faster than usual. Please try again later, I'm sure they will fix it eventually

**Comment by jupiterine** [comment]
I'm having the same issue. Hope this can be fixed.

**Comment by jakubito** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Problems-with-quot-Get-Followed-Artists-quot-API-getting-next/td-p/5513680

**Comment by affinage** [comment]
looks like it's working again
