### ISSUE TITLE
Issue with Updating with Liked Songs

### ISSUE THREAD

**Issue by shelaffs** [jakubito/spotify-release-list#43]
Hello! 

Thanks again for maintaining this site. I've been running into an issue the past few weeks when updating with "Include Artists from Liked Songs" enabled. 

If I disable this option and refresh, everything runs smoothly and new releases are pulled through. If I enable it, there are several errors that are returned. I have included a screenshot when I inspect the page. 

I was hoping this might resolve itself but it's been going on for a few weeks now when I run my weekly update.

Thank you! 

![Screen Shot 2023-05-02 at 1 10 00 PM](https://user-images.githubusercontent.com/44376090/235737614-2e3dc742-b150-4aa7-bde1-f25374f74693.png)

The actual error code says

> {
>   "error": {
>     "status": 401,
>     "message": "No token provided"
>   }
> }

and

> Failed to deserialize query string: missing field `sentry_data`

**Comment by jakubito** [comment]
Hi, thanks for the bug report. I'm unable to fix this right away, but I'll get back to it as soon as I can.

**Comment by jakubito** [comment]
Hi @shelaffs, this should be fixed in the latest version (**3.3.0**)

**Comment by shelaffs** [comment]
Works great, thank you so much! Chipped in a bit to your paypal as thanks. I appreciate you looking into it :)
