### ISSUE TITLE
"No albums to display"

### ISSUE THREAD

**Issue by KatyLB** [jakubito/spotify-release-list#46]
Currently the app is showing "No albums to display" when I scan even though I should of course have lots of results. Not sure when this started, but it was fine two days ago.

**Comment by jupiterine** [comment]
I have a similar issue.

I get new releases, but not all. There should be more, but the refresh only detects half of them. Refreshing again fixes it, but it's annoying having to refresh twice each time.

It started happening since update 3.4.0.

**Comment by jupiterine** [comment]
Update: Ok, now I'm worried. I just refreshed twice and didn't get a single release, despite I know for a fact there should be 2.

**Comment by jakubito** [comment]
Sorry for the problems. I've done some tests and I'm not really sure what's going on. 
1. can you please provide what device + browser you are using?
2. have you tried disabling browser extensions and deleting local app data?
3. have you tried other browsers or devices?
4. do you see any errors?

**Comment by jupiterine** [comment]
Hi. Thanks for replying. I don't know if the reply was meant for me or for KatyLB, but I'll answer nevertheless.

1. Windows 10 with Google Chrome (version 114.0.5735.134)
2. I've tried disabling some extensions, but it didn't work. I haven't deleted app data. 
3. Only a different Chrome profile, with 0 extensions enabled, and with version 3.2.0 (I didn't update it there just in case). Turns out, with version 3.2.0 everything runs smoothly, like it always has. Version 3.4.0 must have a bug.
4. No, I haven't seen any errors.

**Comment by KatyLB** [comment]
> Sorry for the problems. I've done some tests and I'm not really sure what's going on.
> 
>     1. can you please provide what device + browser you are using?
> 
>     2. have you tried disabling browser extensions and deleting local app data?
> 
>     3. have you tried other browsers or devices?
> 
>     4. do you see any errors?

1. Windows 10 with Firefox.
2. I've tried in incognito but I made no changes before it stopped working.
3. I have not but again I made no changes.
4. No errors, just no results.

The scan runs very fast, and perhaps most notably this only started happening after the update, before that it worked perfectly. So something within that update is likely to be the culprit.

**Comment by jakubito** [comment]
I have removed the caching logic I added in the last update. The app version **3.4.1** should now work the same as before. Please let me know if that helped

**Comment by jupiterine** [comment]
I can confirm that version 3.4.1 works perfectly, at least for me. Thanks for taking your time to fix it!

**Comment by KatyLB** [comment]
Yes, it's working again for me now too, thanks!

**Comment by jakubito** [comment]
Excellent
