### ISSUE TITLE
Site says "failed to fetch" when I login with Spotify

### ISSUE THREAD

**Issue by kaem-e** [jakubito/spotify-release-list#47]
Site says "failed to fetch" when I login with Spotify, ive tried clearing cookies etc but nothing sems to work,

**Comment by jakubito** [comment]
The app doesn't use cookies at all. Please check out the [troubleshooting section](https://github.com/jakubito/spotify-release-list#troubleshooting) to see if that helps

**Comment by jakubito** [comment]
Hi @kaem-e, did you get it working?

**Comment by kaem-e** [comment]
Yeah seemed to be an error with edges tracker protection + some extension im sure. I tried with firefox and ublock origin and it seems to work just fine. Sorry i forgot to update before 😅
