### ISSUE TITLE
Feature request: Indicate release type

### ISSUE THREAD

**Issue by S0und** [jakubito/spotify-release-list#5]
Right now there are 4 types we can choose from: Albums, Singles, Compilations, Appearances. Personally i use Albums and Singles. But when you see your results, it's not obvious which result is what. So for example i would like to listen to something, new which would be an album, but those albums are "lost" in the "sea of Singles". 

https://i.imgur.com/GFZfNoh.png

Can we have an icon in front of each result showing the element's type? I'm using text to demo it. 

Thanks!

**Comment by jakubito** [comment]
Hello @S0und,

I tried to implement this before, but eventually scrapped the idea of using icons. I felt the user interface became too cluttered and hard to read. 

I came up with a new idea though - making title colors customizable per group. I think it would solve the problem quite nicely, while still keeping the UI clean. What do you think? 

This is an example of how it could look like (colors would be fully customizable of course):

![Untitled](https://user-images.githubusercontent.com/8123702/100303101-9e9e5d80-2f50-11eb-9e60-08dc65e7249d.jpg)

**Comment by S0und** [comment]
I think it looks fine, does the job well, without adding extra clutter.

**Comment by jakubito** [comment]
This is now available in [v1.8.0](https://github.com/jakubito/spotify-release-list/releases/tag/v1.8.0)
