### ISSUE TITLE
The application is not receiving a complete list of releases

### ISSUE THREAD

**Issue by NewUAM** [jakubito/spotify-release-list#52]
UA -> EN, DeepL, sorry)

Hi, For about the fifth day the application has been receiving an incomplete list of releases, missing most of them. Today I looked in the console and saw 429 error. Is there any way to optimize the process of receiving releases or is this problem only for me because of the number of releases (about 10 000 artists)?

**Comment by jakubito** [comment]
Hi, 429 error is expected. It just means the API rate limit has been hit and client has to wait a couple of seconds. Are you still experiencing the issue?

**Comment by NewUAM** [comment]
The problem with 429 was over a week (I use the service every day). Literally just now managed to get the full track list for the last month without errors (3635 tracks). Do I understand correctly that this error is solely related to my profile due to the large number of artists and requests to the API?

**Comment by jakubito** [comment]
Everybody gets 429 responses, not just you. It's not really an error, more like temporary rejection

**Comment by Kyrluckechuck** [comment]
FWIW I have been running into this a lot recently as well -- it appears it's not retrying the 429 rejections and just moving on, causing about half of the artists I follow to not show up in the summary, and actually having to use Spotify's Release Radar to try to figure out which artists were missed (based on Album/Single release dates)
