### ISSUE TITLE
Specific artist not blocked

### ISSUE THREAD

**Issue by jupiterine** [jakubito/spotify-release-list#54]
Spotify Release List is not blocking a specific artist. This has been happening for months now. 

I even have the ''Exclude Various Artists'' filter activated, but this artist, Summer Hits, is not getting blocked. Am I doing something wrong?

![collage](https://github.com/jakubito/spotify-release-list/assets/71471560/75d5ae54-a3bf-47a2-b405-186f9ba8fd32)

**Comment by jakubito** [comment]
Yeah, I can confirm something's broken.. I'll take a look, thanks

**Comment by jupiterine** [comment]
That's a relief, I thought it was an issue on my end. I hope it can be fixed.

Thanks in advance :)

**Comment by jakubito** [comment]
[v3.6.2](https://github.com/jakubito/spotify-release-list/releases/tag/v3.6.2)
