### ISSUE TITLE
Search only returns few results / running fast

### ISSUE THREAD

**Issue by KatyLB** [jakubito/spotify-release-list#58]
Hi, I believe this is a new issue that has just appeared as the search ran fine yesterday.

When running an update, I only get results for a small number of artists. If I run it again, I get a small number, but then it's different artists. And then a third process gets back to the first ones again. Many are missing that I know should be there in this latest update.

On the first occasion, for example, a new release by The Killers appears, but that is it. There's many releases on a Friday that should be there and are not. On the second occasion, no The Killers release, but results for Quivers and The Linda Lindas. Again, few results and it runs really quickly. At no point do I see, for example, beabadoobee, whose new release is out and should usually appear.

As the search progress goes very quickly so I believe this may be an issue with it not getting all of the artists again as has occurred previously, hopefully a resolvable issue?

**Comment by jupiterine** [comment]
Same here. Yesterday it was working fine, but today is returning less results. The more I refresh, the more releases disappear

**Comment by jakubito** [comment]
Hi, thanks for the report. I'm also experiencing problems with the API throwing random errors. Please give it a few days, it should eventually get resolved by Spotify

**Comment by jupiterine** [comment]
I hope it resolves itself, but I think it's getting worse. Now all I'm getting is the ''No albums to display'' message

![image](https://github.com/user-attachments/assets/972d138d-cbd4-4c8b-a0fe-6d04aa632eba)

**Comment by miikapk** [comment]
Just commenting that it's currently the same for me, hopefully Monday fixes it. Love this app so much & it's became a necessity. Thanks for maintaining it for us jakubito!

**Comment by protonize** [comment]
[workaround](https://community.spotify.com/t5/Spotify-for-Developers/v1-me-following-getting-403s-all-of-a-sudden/td-p/6252827) from Spotify Community

**Comment by jakubito** [comment]
I've increased the retry limit for all API requests in the new version (10 calls per endpoint). Please note this is just a workaround, and it may still fail. We have to wait for Spotify to fix it properly, at least we know it affects other apps too

**Comment by jakubito** [comment]
Is this still an issue? Seems to be working fine now
