### ISSUE TITLE
Feature Request: Ability to filter "EP" from singles and Singles

### ISSUE THREAD

**Issue by rcmpayne** [jakubito/spotify-release-list#61]
After scanning all my data and creating the new music, I'm picking up a lot of EP for albums that already exist and would be nice to filter these out

**Comment by jakubito** [comment]
Can you show me an example of what you are describing? I’m not sure I understand, thanks

**Comment by Totonyus** [comment]
Hi !

Unfortunately Spotify api doesn't makes the difference between EP and albums : https://developer.spotify.com/documentation/web-api/reference/get-an-artists-albums#:~:text=of%20the%20album.-,Allowed%20values%3A%20%22album%22%2C%20%22single%22%2C%20%22compilation%22,-Example%3A%20%22compilation

```
album_type : string -Required
The type of the album.
Allowed values: "album", "single", "compilation"
```
