### ISSUE TITLE
Feature request: Sorting options

### ISSUE THREAD

**Issue by sc113** [jakubito/spotify-release-list#7]
It would be more helpful to sort releases by artist's name for every day instead of release title

**Comment by jakubito** [comment]
@sc113  Are you proposing to keep the alphabetical order of artists within a release and sort by the first one in the list? Trying to figure out how to handle releases with multiple artists 🤔  But I agree, it would be more useful than what we have now

**Comment by jakubito** [comment]
I pushed this change as part of `v1.7.10` release, let me know what you think @sc113

**Comment by sc113** [comment]
Yeah, it looks much better, thank you!

But there are few problems regarding prioritizing main artist or multiple artists:

1) the album's main artist vs collaborations\features. 
- [https://open.spotify.com/album/755yBlrk0Sz8tIgMMTgyr1](https://open.spotify.com/album/755yBlrk0Sz8tIgMMTgyr1)
I follow The Avalanches and most artists from the collaborations on the album. By the logic, it should be filled under the main artist at first - The Avanlances, but instead it's listed under every credited artist sorted alphabetically - "Blood Orange, Jamie xx, Karen O, Kurt Vile, MGMT, Neneh Cherry, The Avalanches". So this album appearing under B instead of T.
- [https://open.spotify.com/album/4Cejj7X43FU8YD9gUROeam](https://open.spotify.com/album/4Cejj7X43FU8YD9gUROeam)
the main artist is slowthai, but it appearing in the list as "James Blake, Mount Kimbie, slowthai"
- [https://open.spotify.com/album/51my18W1EFlHAMZf10r5vn](https://open.spotify.com/album/51my18W1EFlHAMZf10r5vn)
album by WhoMadeWho, but it filled as "Adana Twins, Rebolledo, Robag Wruhme, WhoMadeWho", appearing under A

2) order of album's main artists, when you follow few of them.
- https://open.spotify.com/album/1K91rH2qhN5jscP5pwtx3V
the album is by Nocturnal Sunshine at first as listed on spotify. Maya Jane Coles is an alternative name of the artist, set to connect both profiles. it should appear under N at first, but instead, it filled under M as "Maya Jane Coles, Nocturnal Sunshine"

**Comment by sc113** [comment]
Perhaps, it might be useful if albums were on the list with the main artist as well.

Currently, the list format is: 
#Release title
#Followed artists, #Additional artists & album's artist

But it may be more helpful to use
#Album's artist
#Release title (or #Album's artists - #Release title)
#Followed artists, #Additional artist

And then the whole list sorted by "Album's artist"

It would also help to determine more clearly if the followed artist only participates in someone else's release or if it's their own release.

**Comment by jakubito** [comment]
Hi @sc113,
please check out the newest version `1.7.11`

Followed artists are now ordered by album group they belong to, in this order:
**ALBUM** -> **SINGLE** -> **COMPILATION** -> **APPEARS_ON**

I hope you will find it better than it was before. I know it doesn't solve the second problem you described, but I decided to keep the followed artists being displayed first (the main problem is insufficient data from the API)

**Comment by sc113** [comment]
Yeah, it really became better, and the second case is much less common and not as confusing as the first one, so it is fine. Thank you!
