### ISSUE TITLE
Feature request: Add songs to a pre-existing playlist

### ISSUE THREAD

**Issue by profucius** [jakubito/spotify-release-list#9]
Great app! I use this weekly. I'd really like to be able to add new songs to a pre-existing playlist. Currently, when doing an Export, it asks to create a new playlist. Even if I name the playlist the same as a pre-existing one, it still creates a new playlist with the same name.

Please add this feature into your app! Thanks!

**Comment by jakubito** [comment]
Glad you like the app! The feature you requested would be nice to have but I don't consider it as important as other features on my to-do list (Especially #5 and #3). I'll keep this open as a low priority task.

As a workaround, you can use the desktop Spotify app to select all tracks within a playlist (CMD/CTRL + A) and drag and drop them to your other playlist.

**Comment by profucius** [comment]
Thank you for considering this feature. 

I would like to add the fact that I am requesting this for the purposes of automating my playlist-updating workflow. I use macro tools (e.g. WinAutomation) on my computer to automate clicks, website access, processes, etc. This feature itself would **greatly** improve my workflow, as it would keep everything in a single playlist, removing the need for me to manually delete the newly created playlists each time.

If you have any suggestions that would fit my needs, I'm open to hearing them. Otherwise, I await excitedly to see this feature developed into your app! Thanks

**Comment by jakubito** [comment]
[v3.7.0](https://github.com/jakubito/spotify-release-list/releases/tag/v3.7.0)
